; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = rpi2040

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
lib_extra_dirs = ~/Documents/Arduino/libraries

[env:esp8266]
platform = espressif8266
framework = arduino
board = esp12e
lib_extra_dirs = ~/Documents/Arduino/libraries

[env:rpi2040]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipico
framework = arduino
lib_deps = 
  ; https://github.com/sekigon-gonnoc/Pico-PIO-USB
  ; https://github.com/adafruit/Adafruit_TinyUSB_Arduino@^2.2.2+
lib_archive=no
build_flags = 
  -DUSE_TINYUSB
  -DUSE_TINYUSB_HOST
;  -DCFG_TUSB_CONFIG_FILE=\"tusb_config.h\"
lib_ldf_mode=deep+
